name: Build Python Wheel on PR to Staging

on:
  pull_request:
    branches:
      - staging
    types: [opened, synchronize, reopened]

jobs:
  build_wheel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Use your desired Python version, e.g., '3.9', '3.10', '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build Python wheel
        run: |
          # This command will look for pyproject.toml or setup.py in your repository root.
          # Ensure your setup.py/pyproject.toml correctly points to your 'packages' folder
          # or is configured to include it in the distribution.
          python -m build

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheel
          path: dist/*.whl # Uploads all .whl files found in the dist/ directory